
# --- 👑 CONFIGURACIÓN PRIVADA IMPERIO MP ---

# 🤖 TOKEN DEL BOT DE TELEGRAM
TELEGRAM_TOKEN = "654521622:AAGNVwnlL3lCXwCHi5bVhdTmxwwdv89rR8I" 

# 📲 WHATSAPP DESTINO (ID DEL GRUPO/CANAL)
WHATSAPP_ID = "0029VbC8oCU5Ejy22XI0MM05"

# 📱 TU NÚMERO PRIVADO (Para vinculación inicial)
MY_NUMBER = "5959XXXXXXXX"

# 🎬 MALLY SERIES SETTINGS
MAX_DURATION = 60 # 3 minutos
CAPTION_TEXT = "🔥 *MALLY SERIES* - Nuevo Contenido 😈"

# 📂 RUTAS DEL SISTEMA
BASE_DIR = "media"
VIDEO_TEMP = f"{BASE_DIR}/videos"
HISTORY_DB = f"{BASE_DIR}/history.json"

# ⚙️ AJUSTES DE SISTEMA (Agrega esta línea)
DEBUG = True
