# --- 👑 CONFIGURACIÓN PRIVADA IMPERIO MP ---

# 🤖 TOKEN DEL BOT DE TELEGRAM
TELEGRAM_TOKEN = "" 

# 📲 WHATSAPP DESTINO (ID DEL GRUPO/CANAL)
# Ejemplo: 1234567890-1234567890@g.us
WHATSAPP_ID = "ID_DEL_CANAL_WHATSAPP@g.us"

# 📱 TU NÚMERO PRIVADO (Para vinculación inicial)
# Formato: 5959XXXXXXXX (Sin el +)
MY_NUMBER = "5959XXXXXXXX"

# 🎬 MALLY SERIES SETTINGS
MAX_DURATION = 180  # 3 minutos (Corte automático)
CAPTION_TEXT = "🔥 *MALLY SERIES* - Nuevo Contenido 😈"

# 📂 RUTAS DEL SISTEMA
BASE_DIR = "media"
VIDEO_TEMP = f"{BASE_DIR}/videos"
HISTORY_DB = f"{BASE_DIR}/history.json"
